<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Cinedex.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Email\Assets\cinedex-logo.png"
                        LogicalName="Cinedex.Application.Email.Assets.cinedex-logo.png" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Cinedex.WebService.IntegrationTests" />
    </ItemGroup>

</Project>
