#!/usr/bin/env node
/**
 * Cut a release for the Cinedex repo.
 *
 * Given a decided version, title, and date, this performs the mechanical file
 * surgery for a release so it happens identically every time:
 *
 *   1. root CHANGELOG.md   - move the `## [Unreleased]` body into a new
 *                            `## [x.y.z] - Month D YYYY Title` section and reset
 *                            `## [Unreleased]` to an empty heading. The `--date`
 *                            input is ISO; it is rendered long-form in the heading.
 *   2. backend/Directory.Build.props - set <Version>/<FileVersion>/<InformationalVersion>.
 *   3. frontend/**\/package.json (excluding node_modules) - set "version".
 *
 * The *decision* of what the next version should be is intentionally NOT made
 * here - that requires reading the changelog + git history and applying the
 * CONTRIBUTING.md rules, which the skill does before calling this script.
 *
 * Never touches backend/CHANGELOG.md: it is regenerated by the backend build
 * (the csproj BuildFrontend target copies the root changelog), and CI fails if
 * the two diverge. Run a backend build after releasing and commit that diff.
 *
 * Node 18+ (repo uses Node 22). No dependencies.
 *
 * Usage:
 *   node apply-release.mjs --version 0.6.0 --title "Auth & SMTP" [--date 2026-07-18]
 *                          [--repo-root .] [--dry-run]
 *
 * Exit codes: 0 ok, 2 usage/validation error.
 */
import fs from "node:fs";
import path from "node:path";

const SEMVER_RE = /^\d+\.\d+\.\d+$/;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const PROP_TAGS = ["Version", "FileVersion", "InformationalVersion"];
const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/**
 * Render an ISO `YYYY-MM-DD` date as `Month D YYYY` (e.g. 2026-07-18 -> "July 18
 * 2026"). Built from the string parts rather than `new Date()` to avoid any
 * timezone shift. The `--date` input stays ISO; only the display form changes.
 */
function formatDisplayDate(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return `${MONTHS[m - 1]} ${d} ${y}`;
}

function die(msg) {
  console.error(`error: ${msg}`);
  process.exit(2);
}

function parseArgs(argv) {
  const out = { dryRun: false, repoRoot: ".", date: new Date().toISOString().slice(0, 10) };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--dry-run") out.dryRun = true;
    else if (a === "--version") out.version = argv[++i];
    else if (a === "--title") out.title = argv[++i];
    else if (a === "--date") out.date = argv[++i];
    else if (a === "--repo-root") out.repoRoot = argv[++i];
    else die(`unknown argument: ${a}`);
  }
  if (!out.version) die("--version is required");
  if (!out.title) die("--title is required");
  return out;
}

function parseSemver(v) {
  if (!SEMVER_RE.test(v)) die(`'${v}' is not a MAJOR.MINOR.PATCH version`);
  return v.split(".").map(Number);
}

/** true if a > b for [major, minor, patch] triples */
function gt(a, b) {
  for (let i = 0; i < 3; i++) {
    if (a[i] > b[i]) return true;
    if (a[i] < b[i]) return false;
  }
  return false;
}

// --------------------------------------------------------------------------- //
// CHANGELOG.md
// --------------------------------------------------------------------------- //
/**
 * Move the Unreleased body under a new dated version heading.
 *
 * Line-based on purpose: the changelog uses `---` separators between sections,
 * and a naive regex risks swallowing them. We locate the Unreleased heading and
 * the next `## [` heading, lift the content in between (dropping the trailing
 * separator), and rebuild the top with consistent spacing.
 */
function cutChangelog(text, version, date, title) {
  const lines = text.split("\n");

  const i = lines.findIndex((ln) => ln.trim() === "## [Unreleased]");
  if (i === -1) die("no '## [Unreleased]' heading found in CHANGELOG.md");

  let j = lines.length;
  for (let n = i + 1; n < lines.length; n++) {
    if (lines[n].startsWith("## [")) {
      j = n;
      break;
    }
  }

  let body = lines.slice(i + 1, j);
  // Strip surrounding blanks and a trailing `---`; we re-add our own separators.
  while (body.length && body[0].trim() === "") body.shift();
  while (body.length && body[body.length - 1].trim() === "") body.pop();
  if (body.length && body[body.length - 1].trim() === "---") body.pop();
  while (body.length && body[body.length - 1].trim() === "") body.pop();

  if (body.length === 0) {
    die(
      "nothing to release: the '## [Unreleased]' section is empty. " +
        "Add changelog entries before cutting a release.",
    );
  }

  const heading = `## [${version}] - ${formatDisplayDate(date)} ${title}`.trimEnd();
  const newTop = [
    "## [Unreleased]",
    "",
    "---",
    "",
    heading,
    "",
    ...body,
    "",
    "---",
    "",
  ];

  const rebuilt = [...lines.slice(0, i), ...newTop, ...lines.slice(j)];
  // Collapse any accidental 4+ newline runs at the seams down to a blank line.
  return rebuilt.join("\n").replace(/\n{4,}/g, "\n\n\n");
}

// --------------------------------------------------------------------------- //
// Directory.Build.props
// --------------------------------------------------------------------------- //
function bumpProps(text, version) {
  for (const tag of PROP_TAGS) {
    const re = new RegExp(`(<${tag}>)[^<]*(</${tag}>)`);
    if (!re.test(text)) die(`<${tag}> not found in Directory.Build.props`);
    text = text.replace(re, `$1${version}$2`);
  }
  return text;
}

// --------------------------------------------------------------------------- //
// package.json (targeted replace - never reserialize, to avoid formatting churn)
// --------------------------------------------------------------------------- //
function bumpPackageJson(text, version) {
  const re = /("version"\s*:\s*")[^"]*(")/;
  if (!re.test(text)) die('"version" field not found in package.json');
  return text.replace(re, `$1${version}$2`);
}

function findFrontendPackageJsons(repoRoot) {
  const frontend = path.join(repoRoot, "frontend");
  if (!fs.existsSync(frontend)) return [];
  const results = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "node_modules") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name === "package.json") results.push(full);
    }
  };
  walk(frontend);
  return results;
}

// --------------------------------------------------------------------------- //
function main() {
  const args = parseArgs(process.argv.slice(2));
  const newV = parseSemver(args.version);
  if (!ISO_DATE_RE.test(args.date)) die(`--date '${args.date}' is not ISO YYYY-MM-DD`);

  const root = path.resolve(args.repoRoot);
  const changelogPath = path.join(root, "CHANGELOG.md");
  const propsPath = path.join(root, "backend", "Directory.Build.props");

  if (!fs.existsSync(changelogPath)) die(`${changelogPath} not found (is --repo-root correct?)`);
  if (!fs.existsSync(propsPath)) die(`${propsPath} not found (is --repo-root correct?)`);

  const propsText = fs.readFileSync(propsPath, "utf8");
  const curMatch = propsText.match(/<Version>([^<]*)<\/Version>/);
  if (curMatch) {
    const cur = parseSemver(curMatch[1].trim());
    if (!gt(newV, cur)) {
      die(`new version ${args.version} is not greater than current ${cur.join(".")}`);
    }
  }

  // Build all new contents up front so a validation failure aborts cleanly
  // before any file is written.
  const changelogNew = cutChangelog(
    fs.readFileSync(changelogPath, "utf8"),
    args.version,
    args.date,
    args.title,
  );
  const propsNew = bumpProps(propsText, args.version);
  const pkgPaths = findFrontendPackageJsons(root);
  const pkgNew = pkgPaths.map((p) => [p, bumpPackageJson(fs.readFileSync(p, "utf8"), args.version)]);

  const targets = [
    [changelogPath, changelogNew],
    [propsPath, propsNew],
    ...pkgNew,
  ];

  const rel = (p) => path.relative(root, p).replace(/\\/g, "/");

  const displayDate = formatDisplayDate(args.date);

  if (args.dryRun) {
    console.log(`PLAN: release ${args.version} - ${displayDate} ${args.title}\n`);
    console.log(`  CHANGELOG.md          new '## [${args.version}] - ${displayDate} ${args.title}' section`);
    console.log(`  Directory.Build.props Version/FileVersion/InformationalVersion -> ${args.version}`);
    if (pkgPaths.length === 0) console.log("  (no frontend package.json found)");
    for (const p of pkgPaths) console.log(`  ${rel(p)}  version -> ${args.version}`);
    console.log("\nNew changelog top (first 40 lines):\n");
    console.log(changelogNew.split("\n").slice(0, 40).join("\n"));
    console.log("\n(dry run - no files written)");
    return;
  }

  for (const [p, content] of targets) {
    fs.writeFileSync(p, content);
    console.log(`updated ${rel(p)}`);
  }

  console.log(`\nreleased ${args.version} - ${displayDate} ${args.title}`);
  console.log("reminders:");
  console.log("  - run a backend build so backend/CHANGELOG.md refreshes, then commit that diff");
  console.log("  - run `npm install --package-lock-only` in the frontend to sync package-lock.json");
}

main();
