// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Persistence.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Persistence.Postgres.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20260622185711_AddGenres")]
    partial class AddGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movies.Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Description = "Action genre featuring physical conflict and adventure.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Description = "Comedy genre focused on humor and entertainment.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Description = "Drama genre focused on emotional storytelling.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Description = "Fantasy genre with magical and imaginative elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Description = "Horror genre designed to evoke fear.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Description = "Romance genre focused on relationships and love.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Description = "Science fiction genre exploring futuristic or scientific concepts.",
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Description = "Thriller genre designed to create suspense.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Description = "Animation genre using animated characters and storytelling.",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110a"),
                            Description = "Adventure genre featuring exploration and quests.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110b"),
                            Description = "Crime genre focused on criminal activities and investigations.",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110c"),
                            Description = "Documentary genre presenting factual information.",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110d"),
                            Description = "Family genre appropriate for all ages.",
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110e"),
                            Description = "History genre based on historical events.",
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110f"),
                            Description = "Musical genre featuring songs and musical performances.",
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Description = "Mystery genre focused on solving puzzles or crimes.",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Western genre set in the Old West.",
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("Movies.Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_release");

                    b.HasKey("Id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("movie_genres", b =>
                {
                    b.Property<Guid>("genre_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("movie_id")
                        .HasColumnType("uuid");

                    b.HasKey("genre_id", "movie_id");

                    b.HasIndex("movie_id");

                    b.ToTable("movie_genres");
                });

            modelBuilder.Entity("movie_genres", b =>
                {
                    b.HasOne("Movies.Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Domain.Movie", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
