// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Persistence.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Persistence.Postgres.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20260623030244_RemoveGenreDescription")]
    partial class RemoveGenreDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movies.Domain.GenreAggregate.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110a"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110b"),
                            Name = "Crime"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110c"),
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110d"),
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110e"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111110f"),
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("Movies.Domain.MovieAggregate.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<Guid>>("GenreIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("genre_ids");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_release");

                    b.HasKey("Id");

                    b.ToTable("movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
