<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="SSH.NET" PrivateAssets="all" />
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="LiquidTestReports.Markdown" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Presentation\Cinedex.WebService\Cinedex.WebService.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Endpoints\" />
    </ItemGroup>

</Project>
